import RootProvider from "@/providers/RootProvider";
import type { Metadata } from "next";
import "./globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ko">
      <body>
        <div id="backdrop-hook"></div>
        <div id="modal-hook"></div>
        <RootProvider>{children}</RootProvider>
      </body>
    </html>
  );
}
